from langchain_openai import ChatOpenAI
import os
from dotenv import load_dotenv
import logging

# Load environment variables
load_dotenv()

# Configure logging
logger = logging.getLogger(__name__)

# Get API key from environment
openai_api_key = os.getenv("OPENAI_API_KEY")
if not openai_api_key:
    raise ValueError("OPENAI_API_KEY not found in environment variables")

hb_cta_agent_template = {
    "lead_researcher": {
        "role": "Lead Researcher",
        "goal": "Get relevant client details for the given offer",
        "backstory": "You are a researcher specialising in researching and profiling leads."
        "You extract relevant information about leads from the given data that will help in generating personalised "
        "email for cold out reach.",
        "allow_delegation": False,
        "llm": ChatOpenAI(model="gpt-3.5-turbo", temperature=0),
    },
    "company_researcher": {
        "role": "Company Researcher",
        "goal": "Get relevant client company information details for the given offer",
        "backstory": "You are a researcher specialising in researching and profiling client companies."
        "You extract relevant information about a client company from the given data that will help "
        "in generating personalised email for cold out reach.",
        "allow_delegation": False,
        "llm": ChatOpenAI(model="gpt-3.5-turbo", temperature=0),
    },
    "hook_body_writer": {
        "role": "Email hook and body Writer",
        "goal": "Write personalised hook and body of a cold email that will be sent to a lead",
        "backstory": "You are an experienced email writer specialising in writing personalised cold emails to leads."
        "You will use the information provided by the  Lead Researcher and the Company Researcher to write two "
        "important parts of a personalised cold email: "
        "1. The Hook: The hook is ideally the first one or two sentences of the email written to get the lead's attention"
        "2. The body: The body describes the product or service offered to the lead.",
        "allow_delegation": False,
        "llm": ChatOpenAI(model="gpt-3.5-turbo", temperature=0.7),
    },
    "cta_writer": {
        "role": "Email Call to Action writer",
        "goal": "Write professional call to action for a personalised cold email that will be sent to a lead",
        "backstory": "You are an experienced email writer specialising in writing personalised cold emails to leads."
        "You will use the information provided by the Email hook and body Writer and the given call-to-action to write "
        "a call to action for the cold email. Here is the call to action that I want: {cta}",
        "allow_delegation": False,
        "llm": ChatOpenAI(model="gpt-3.5-turbo", temperature=0.3),
    },
    "email_compiler": {
        "role": "Email compiler",
        "goal": "Validate and generate the final email",
        "backstory": "You are the lead of the cold email campaign. You will use the information provided by the "
        "Email hook and body Writer and Email Call to Action writer to generate the final email and"
        "validate it to make sure it is professional.",
        "allow_delegation": False,
        "llm": ChatOpenAI(model="gpt-4", temperature=0.5),
    },
    # "email_validator": {
    #     "role": "Email validator",
    #     "goal": "Validate the final email",
    #     "backstory": "You are the manager of the cold email campaign. You will validate the final email"
    #     "generated by the Email compiler to make sure it is professional.",
    #     "allow_delegation": False,
    # },
}

hb_cta_task_template = {
    "lead_profiling_task": {
        "description": "1. Analyze the lead's LinkedIn profile information: {linkedin_profile}"
        "2. Review the offer details: {offer}"
        "3. Generate 2-3 pain points that can be used to write an email hook using the profile and offer details (call these 'lead-pain points')",
        "expected_output": "Point wise lead pain points",
    },
    "company_profiling_task": {
        "description": "1.Understand the information extracted from the lead's company profile here: {company_profile}."
        "2.Understand the offer that I am trying to sell here: {offer}."
        "3.Identify 2-3 pain points of the company that can be solved by the offer. You can assume "
        "general best practices and challenges faced by this business to identify pain points."
        "Let's call them 'company-pain points'",
        "expected_output": "Point wise company pain points",
    },
    "hook_body_writing_task": {
        "description": "1. hook_offer_combination_1: Write a hook for a cold email using the company-pain points. "
        "Add a short paragraph clearly stating the offer and how it helps them."
        " "
        "2. hook_offer_combination_2: Write a hook for a cold email using the lead-pain points. "
        "Add a short paragraph clearly stating the offer and how it helps them."
        " "
        "Make sure the hooks are attention grabing for a human and is less than 20 words. Make sure they are not too generic and hyper personalised."
        "Make sure the offer description (in the second paragraph) is short and to the point and is less than 40 words."
        "Here is the offer: {offer}",
        "expected_output": "2 Professional hooks/openers and respective offers of a personalised cold email",
    },
    "cta_writing_task": {
        "description": "Write a one or two liner call to action for the email. If the {cta} includes a link, "
        "redirect the user to the link. Make sure the cta is less than 25 words.",
        "expected_output": "Professional call to action of a personalised cold email",
    },
    "final_email_task": {
        "description": "Choose one of hook_offer_combination_1 or hook_offer_combination_2 that is more attention grabbing for a human "
        "and combine it with the cta and then the closing signature creating the full email. Do not further modify the hooks or the offer description. "
        "The name of the lead is {lead_name}. The sender of this email is {seller_name}."
        "Make sure the email is less than 80 words.",
        "expected_output": "1. The subject of the email. 2. The email. In this format: Subject: <subject> Email: <email>",
    },
    # "email_validation_task": {
    #     "description": "Validate the final email to make sure it is "
    #     "1. Professional but not too formal. 2. Follows the format of a cold email. "
    #     "3. Is not too generic. 4. Looks like it is written by a human."
    #     "Once validated, return the email in the following format: Subject: <subject> Email: <email>"
    #     "Otherwise delegate the task back to the Email compiler to fix the issues.",
    #     "expected_output": "The final email in the format: Subject: <subject> Email: <email>",
    # }
}

task_agent_mapping = {
    "lead_profiling_task": "lead_researcher",
    "company_profiling_task": "company_researcher",
    "hook_body_writing_task": "hook_body_writer",
    "cta_writing_task": "cta_writer",
    "final_email_task": "email_compiler",
    # "email_validation_task": "email_validator",
}

# Agent templates for email generation crew
email_agents = {
    "profile_analyzer": {
        "role": "LinkedIn Profile Analyzer",
        "goal": "Extract key insights from LinkedIn profiles for personalized outreach",
        "backstory": "You are an expert at analyzing professional profiles to identify opportunities "
                    "for personalized outreach. You can quickly identify achievements, skills, and potential "
                    "challenges that can be addressed in a cold email.",
        "allow_delegation": False,
        "llm": ChatOpenAI(model="gpt-4", temperature=0.2),
    },
    "company_researcher": {
        "role": "Company Intelligence Specialist",
        "goal": "Identify company needs and pain points relevant to our solution",
        "backstory": "You specialize in company research and understanding industry challenges. "
                    "You can identify specific ways our solution can bring value to a target company "
                    "based on their size, industry, and growth stage.",
        "allow_delegation": False,
        "llm": ChatOpenAI(model="gpt-4", temperature=0.2),
    },
    "email_writer": {
        "role": "Personalized Email Composer",
        "goal": "Craft attention-grabbing, personalized emails that generate responses",
        "backstory": "You are an expert email copywriter specialized in B2B outreach. You know how to create "
                    "concise, highly personalized emails that demonstrate research and offer clear value without "
                    "using generic language.",
        "allow_delegation": False,
        "llm": ChatOpenAI(model="gpt-4", temperature=0.7),
    },
    "quality_controller": {
        "role": "Email Quality Assurance",
        "goal": "Ensure all emails are professional, error-free, and persuasive",
        "backstory": "You review cold emails for quality, ensuring they are concise, free of "
                    "errors, appropriately personalized, and effectively communicate value while avoiding "
                    "spam triggers and maintaining a professional tone.",
        "allow_delegation": False,
        "llm": ChatOpenAI(model="gpt-4", temperature=0.1),
    }
}

# Task templates with clear expected outputs
email_tasks = {
    "profile_analysis_task": {
        "description": "Analyze this LinkedIn profile: \n\n"
                      "{linkedin_profile}\n\n"
                      "Based on this information:\n"
                      "1. Identify 2-3 specific professional challenges this person likely faces\n"
                      "2. Note any recent achievements or career milestones that could be mentioned\n"
                      "3. Determine their likely seniority level and decision-making authority\n"
                      "4. Given our offer: {offer}, what specific value would most resonate with them?",
        "expected_output": "A structured analysis with clear bullet points for each category"
    },
    "company_analysis_task": {
        "description": "Research this company based on available information:\n\n"
                      "{company_profile}\n\n"
                      "Based on this company and your knowledge of similar organizations:\n"
                      "1. What are the top 2-3 challenges this company likely faces that our solution could address?\n"
                      "2. What stage of growth is this company likely in?\n"
                      "3. What competitive pressures might they be experiencing?\n"
                      "4. Given our offer: {offer}, what specific company-wide benefits would they value most?",
        "expected_output": "A structured company analysis with industry-specific insights"
    },
    "email_creation_task": {
        "description": "Create a personalized cold email using these insights:\n\n"
                      "Recipient: {lead_name}\n"
                      "Profile insights: {profile_analysis_result}\n"
                      "Company insights: {company_analysis_result}\n"
                      "Our offer: {offer}\n\n"
                      "Guidelines:\n"
                      "- Keep the email under 100 words total\n"
                      "- Start with a highly personalized opening line referencing specific profile details\n"
                      "- Focus on ONE specific pain point most relevant to them\n"
                      "- Clearly state the value proposition in business outcome terms\n"
                      "- End with this call to action: {cta}\n"
                      "- Sign as: {seller_name}\n\n"
                      "IMPORTANT: Format your response exactly like this:\n"
                      "Subject: [Your subject line]\n"
                      "Email: [Your email body]",
        "expected_output": "A complete email with subject line and body in the exact format specified"
    },
    "quality_control_task": {
        "description": "Review this cold email for quality and effectiveness:\n\n"
                      "{email_creation_result}\n\n"
                      "Check for:\n"
                      "1. Personalization level\n"
                      "2. Length (under 100 words?)\n"
                      "3. Value clarity\n"
                      "4. Call to action clarity\n"
                      "5. Overall tone\n"
                      "6. Grammar and spelling\n\n"
                      "IMPORTANT: Return the final email in exactly this format:\n"
                      "Subject: [subject]\n"
                      "Email: [email body]",
        "expected_output": "The final approved email in the exact format: Subject: [subject] followed by Email: [email body]"
    }
}

# Mapping tasks to agents
task_agent_mapping = {
    "profile_analysis_task": "profile_analyzer",
    "company_analysis_task": "company_researcher",
    "email_creation_task": "email_writer",
    "quality_control_task": "quality_controller"
}

# Email parsing function
def parse_email(email_text):
    """
    Parse the generated email text to extract subject and body
    
    Returns:
        tuple: (subject, body)
    """
    if not email_text:
        logger.error("Email text is empty")
        return None, None
        
    logger.info(f"Raw email text to parse: {email_text}")
    
    lines = email_text.strip().split('\n')
    subject = ""
    body = ""
    
    # Try to find subject and email markers
    subject_found = False
    email_found = False
    
    for i, line in enumerate(lines):
        line = line.strip()
        
        # Look for subject line
        if line.lower().startswith("subject:"):
            subject = line[8:].strip()
            subject_found = True
            logger.info(f"Found subject: {subject}")
            
        # Look for email body
        elif line.lower().startswith("email:"):
            email_start_idx = line.find(':') + 1
            body = line[email_start_idx:].strip()
            email_found = True
            
            # If body continues on next lines, capture them
            body_lines = []
            for next_line in lines[i+1:]:
                next_line = next_line.strip()
                if next_line.lower().startswith("subject:"):
                    break
                if next_line:  # Only add non-empty lines
                    body_lines.append(next_line)
            
            if body_lines:
                body = body + "\n" + "\n".join(body_lines)
            
            logger.info(f"Found email body: {body}")
            break
    
    if not subject_found:
        logger.error("No subject line found in email text")
    if not email_found:
        logger.error("No email body found in email text")
        
    return subject, body